dv - | CRITICAL flwr 2024-10-13 11:57:10,259 | server_app.py:85 | file writing: True
dv - | CRITICAL flwr 2024-10-13 11:57:10,259 | server_app.py:86 | running in fed_wide
dv - | CRITICAL flwr 2024-10-13 11:57:10,260 | server_app.py:87 | min num clients 2
dv - | CRITICAL flwr 2024-10-13 11:57:10,260 | server_app.py:88 | num server rounds 1
dv - | CRITICAL flwr 2024-10-13 11:57:10,261 | server_app.py:89 | num local epochs 2
dv - | CRITICAL flwr 2024-10-13 11:57:10,261 | server_app.py:90 | advanced logging False
dv - | INFO flwr 2024-10-13 11:57:10,262 | app.py:74 | Starting Flower ServerApp, config: num_rounds=1, no round_timeout
dv - | INFO flwr 2024-10-13 11:57:10,262 | app.py:79 | 
dv - | INFO flwr 2024-10-13 11:57:10,264 | server.py:92 | [INIT]
dv - | INFO flwr 2024-10-13 11:57:10,264 | server.py:277 | Using initial global parameters provided by strategy
dv - | INFO flwr 2024-10-13 11:57:10,265 | server.py:94 | Starting evaluation of initial global parameters
dv - | CRITICAL flwr 2024-10-13 11:57:10,265 | fed_wide.py:40 | Evaluation has ran!
dv - | ERROR flwr 2024-10-13 11:57:10,267 | run_simulation.py:344 | ServerApp thread raised an exception: FedWide.custom_eval() takes 3 positional arguments but 4 were given
dv - | ERROR flwr 2024-10-13 11:57:10,271 | run_simulation.py:345 | Traceback (most recent call last):
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\simulation\run_simulation.py", line 336, in server_th_with_start_checks
    run_server_app(
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\run_serverapp.py", line 88, in run
    server_app(driver=driver, context=context)
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server_app.py", line 120, in __call__
    start_driver(
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\compat\app.py", line 87, in start_driver
    hist = run_fl(
           ^^^^^^^
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server.py", line 492, in run_fl
    hist, elapsed_time = server.fit(
                         ^^^^^^^^^^^
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server.py", line 95, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hughj\Documents\GitHub\asfl\asfl\strats\fed_wide.py", line 47, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: FedWide.custom_eval() takes 3 positional arguments but 4 were given

dv - | DEBUG flwr 2024-10-13 11:57:10,274 | run_simulation.py:349 | ServerApp finished running.
dv - | DEBUG flwr 2024-10-13 11:57:10,274 | run_simulation.py:353 | Triggered stop event for Simulation Engine.
dv - | DEBUG flwr 2024-10-13 11:57:17,399 | raybackend.py:141 | Constructed ActorPool with: 6 actors
dv - | DEBUG flwr 2024-10-13 11:57:17,399 | state_factory.py:50 | Using InMemoryState
dv - | DEBUG flwr 2024-10-13 11:57:17,403 | ray_actor.py:450 | Terminated 6 actors
dv - | DEBUG flwr 2024-10-13 11:57:18,121 | raybackend.py:193 | Terminated RayBackend
dv - | CRITICAL flwr 2024-10-13 11:58:16,132 | server_app.py:85 | file writing: True
dv - | CRITICAL flwr 2024-10-13 11:58:16,132 | server_app.py:86 | running in fed_wide
dv - | CRITICAL flwr 2024-10-13 11:58:16,132 | server_app.py:87 | min num clients 2
dv - | CRITICAL flwr 2024-10-13 11:58:16,132 | server_app.py:88 | num server rounds 1
dv - | CRITICAL flwr 2024-10-13 11:58:16,133 | server_app.py:89 | num local epochs 2
dv - | CRITICAL flwr 2024-10-13 11:58:16,133 | server_app.py:90 | advanced logging False
dv - | INFO flwr 2024-10-13 11:58:16,133 | app.py:74 | Starting Flower ServerApp, config: num_rounds=1, no round_timeout
dv - | INFO flwr 2024-10-13 11:58:16,134 | app.py:79 | 
dv - | INFO flwr 2024-10-13 11:58:16,135 | server.py:92 | [INIT]
dv - | INFO flwr 2024-10-13 11:58:16,135 | server.py:277 | Using initial global parameters provided by strategy
dv - | INFO flwr 2024-10-13 11:58:16,135 | server.py:94 | Starting evaluation of initial global parameters
dv - | CRITICAL flwr 2024-10-13 11:58:16,135 | fed_wide.py:40 | Evaluation has ran!
dv - | CRITICAL flwr 2024-10-13 11:58:16,136 | fed_wide.py:51 | eval found global15
dv - | INFO flwr 2024-10-13 11:58:16,137 | server.py:97 | initial parameters (loss, other metrics): 15, 3
dv - | ERROR flwr 2024-10-13 11:58:16,137 | run_simulation.py:344 | ServerApp thread raised an exception: 'int' object is not iterable
dv - | ERROR flwr 2024-10-13 11:58:16,153 | run_simulation.py:345 | Traceback (most recent call last):
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\simulation\run_simulation.py", line 336, in server_th_with_start_checks
    run_server_app(
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\run_serverapp.py", line 88, in run
    server_app(driver=driver, context=context)
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server_app.py", line 120, in __call__
    start_driver(
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\compat\app.py", line 87, in start_driver
    hist = run_fl(
           ^^^^^^^
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server.py", line 492, in run_fl
    hist, elapsed_time = server.fit(
                         ^^^^^^^^^^^
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server.py", line 104, in fit
    history.add_metrics_centralized(server_round=0, metrics=res[1])
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\history.py", line 69, in add_metrics_centralized
    for key in metrics:
               ^^^^^^^
TypeError: 'int' object is not iterable

dv - | DEBUG flwr 2024-10-13 11:58:16,156 | run_simulation.py:349 | ServerApp finished running.
dv - | DEBUG flwr 2024-10-13 11:58:16,156 | run_simulation.py:353 | Triggered stop event for Simulation Engine.
dv - | DEBUG flwr 2024-10-13 11:58:23,117 | raybackend.py:141 | Constructed ActorPool with: 6 actors
dv - | DEBUG flwr 2024-10-13 11:58:23,118 | state_factory.py:50 | Using InMemoryState
dv - | DEBUG flwr 2024-10-13 11:58:23,122 | ray_actor.py:450 | Terminated 6 actors
dv - | DEBUG flwr 2024-10-13 11:58:23,906 | raybackend.py:193 | Terminated RayBackend
dv - | CRITICAL flwr 2024-10-13 12:00:20,071 | server_app.py:85 | file writing: True
dv - | CRITICAL flwr 2024-10-13 12:00:20,072 | server_app.py:86 | running in fed_wide
dv - | CRITICAL flwr 2024-10-13 12:00:20,072 | server_app.py:87 | min num clients 2
dv - | CRITICAL flwr 2024-10-13 12:00:20,073 | server_app.py:88 | num server rounds 1
dv - | CRITICAL flwr 2024-10-13 12:00:20,073 | server_app.py:89 | num local epochs 2
dv - | CRITICAL flwr 2024-10-13 12:00:20,073 | server_app.py:90 | advanced logging False
dv - | INFO flwr 2024-10-13 12:00:20,073 | app.py:74 | Starting Flower ServerApp, config: num_rounds=1, no round_timeout
dv - | INFO flwr 2024-10-13 12:00:20,074 | app.py:79 | 
dv - | INFO flwr 2024-10-13 12:00:20,075 | server.py:92 | [INIT]
dv - | INFO flwr 2024-10-13 12:00:20,075 | server.py:277 | Using initial global parameters provided by strategy
dv - | INFO flwr 2024-10-13 12:00:20,075 | server.py:94 | Starting evaluation of initial global parameters
dv - | CRITICAL flwr 2024-10-13 12:00:20,075 | fed_wide.py:40 | Evaluation has ran!
dv - | CRITICAL flwr 2024-10-13 12:00:20,077 | fed_wide.py:51 | eval found global15
dv - | INFO flwr 2024-10-13 12:00:20,077 | server.py:97 | initial parameters (loss, other metrics): 15, {'central_acc': 0.501}
dv - | INFO flwr 2024-10-13 12:00:20,077 | server.py:112 | 
dv - | INFO flwr 2024-10-13 12:00:20,077 | server.py:113 | [ROUND 1]
dv - | INFO flwr 2024-10-13 12:00:20,078 | server.py:226 | configure_fit: strategy sampled 4 clients (out of 5)
dv - | DEBUG flwr 2024-10-13 12:00:26,759 | raybackend.py:141 | Constructed ActorPool with: 6 actors
dv - | DEBUG flwr 2024-10-13 12:00:26,760 | state_factory.py:50 | Using InMemoryState
dv - | INFO flwr 2024-10-13 12:01:00,756 | server.py:240 | aggregate_fit: received 4 results and 0 failures
dv - | WARNING flwr 2024-10-13 12:01:00,760 | fedavg.py:252 | No fit_metrics_aggregation_fn provided
dv - | CRITICAL flwr 2024-10-13 12:01:00,760 | fed_wide.py:40 | Evaluation has ran!
dv - | CRITICAL flwr 2024-10-13 12:01:00,763 | fed_wide.py:51 | eval found global15
dv - | INFO flwr 2024-10-13 12:01:00,764 | server.py:131 | fit progress: (1, 15, {'central_acc': 0.501}, 40.69065170000249)
dv - | INFO flwr 2024-10-13 12:01:00,764 | server.py:178 | configure_evaluate: strategy sampled 4 clients (out of 5)
dv - | INFO flwr 2024-10-13 12:01:02,772 | server.py:192 | aggregate_evaluate: received 4 results and 0 failures
dv - | INFO flwr 2024-10-13 12:01:02,773 | server.py:496 | 
dv - | INFO flwr 2024-10-13 12:01:02,773 | server.py:497 | [SUMMARY]
dv - | INFO flwr 2024-10-13 12:01:02,774 | server.py:498 | Run finished 1 round(s) in 42.70s
dv - | INFO flwr 2024-10-13 12:01:02,774 | server.py:500 | 	History (loss, distributed):
dv - | INFO flwr 2024-10-13 12:01:02,774 | server.py:500 | 		round 1: 147.491149342709
dv - | INFO flwr 2024-10-13 12:01:02,775 | server.py:500 | 	History (loss, centralized):
dv - | INFO flwr 2024-10-13 12:01:02,775 | server.py:500 | 		round 0: 15
dv - | INFO flwr 2024-10-13 12:01:02,775 | server.py:500 | 		round 1: 15
dv - | INFO flwr 2024-10-13 12:01:02,775 | server.py:500 | 	History (metrics, distributed, evaluate):
dv - | INFO flwr 2024-10-13 12:01:02,776 | server.py:500 | 	{'accuracy': [(1, 0.12424395161290322)], 'count': [(1, 4)]}
dv - | INFO flwr 2024-10-13 12:01:02,776 | server.py:500 | 	History (metrics, centralized):
dv - | INFO flwr 2024-10-13 12:01:02,776 | server.py:500 | 	{'central_acc': [(0, 0.501), (1, 0.501)]}
dv - | INFO flwr 2024-10-13 12:01:02,776 | server.py:501 | 
dv - | DEBUG flwr 2024-10-13 12:01:02,778 | run_serverapp.py:90 | ServerApp finished running.
dv - | DEBUG flwr 2024-10-13 12:01:02,778 | run_simulation.py:349 | ServerApp finished running.
dv - | DEBUG flwr 2024-10-13 12:01:02,778 | run_simulation.py:353 | Triggered stop event for Simulation Engine.
dv - | DEBUG flwr 2024-10-13 12:01:03,757 | ray_actor.py:450 | Terminated 6 actors
dv - | DEBUG flwr 2024-10-13 12:01:04,578 | raybackend.py:193 | Terminated RayBackend
dv - | DEBUG flwr 2024-10-13 12:01:04,578 | run_simulation.py:455 | Stopping Simulation Engine now.
dv - | CRITICAL flwr 2024-10-13 12:03:01,146 | server_app.py:85 | file writing: True
dv - | CRITICAL flwr 2024-10-13 12:03:01,147 | server_app.py:86 | running in fed_agg
dv - | CRITICAL flwr 2024-10-13 12:03:01,148 | server_app.py:87 | min num clients 2
dv - | CRITICAL flwr 2024-10-13 12:03:01,148 | server_app.py:88 | num server rounds 1
dv - | CRITICAL flwr 2024-10-13 12:03:01,149 | server_app.py:89 | num local epochs 2
dv - | CRITICAL flwr 2024-10-13 12:03:01,152 | server_app.py:90 | advanced logging False
dv - | INFO flwr 2024-10-13 12:03:01,153 | app.py:74 | Starting Flower ServerApp, config: num_rounds=1, no round_timeout
dv - | INFO flwr 2024-10-13 12:03:01,153 | app.py:79 | 
dv - | INFO flwr 2024-10-13 12:03:01,154 | server.py:92 | [INIT]
dv - | INFO flwr 2024-10-13 12:03:01,155 | server.py:277 | Using initial global parameters provided by strategy
dv - | INFO flwr 2024-10-13 12:03:01,155 | server.py:94 | Starting evaluation of initial global parameters
dv - | ERROR flwr 2024-10-13 12:03:01,155 | run_simulation.py:344 | ServerApp thread raised an exception: 'FedAgg' object has no attribute 'net'
dv - | ERROR flwr 2024-10-13 12:03:01,158 | run_simulation.py:345 | Traceback (most recent call last):
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\simulation\run_simulation.py", line 336, in server_th_with_start_checks
    run_server_app(
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\run_serverapp.py", line 88, in run
    server_app(driver=driver, context=context)
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server_app.py", line 120, in __call__
    start_driver(
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\compat\app.py", line 87, in start_driver
    hist = run_fl(
           ^^^^^^^
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server.py", line 492, in run_fl
    hist, elapsed_time = server.fit(
                         ^^^^^^^^^^^
  File "C:\Users\hughj\Documents\GitHub\asfl\venv\Lib\site-packages\flwr\server\server.py", line 95, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hughj\Documents\GitHub\asfl\asfl\strats\fed_custom.py", line 247, in evaluate
    set_weights(self.net, parameters)
                ^^^^^^^^
AttributeError: 'FedAgg' object has no attribute 'net'

dv - | DEBUG flwr 2024-10-13 12:03:01,161 | run_simulation.py:349 | ServerApp finished running.
dv - | DEBUG flwr 2024-10-13 12:03:01,161 | run_simulation.py:353 | Triggered stop event for Simulation Engine.
dv - | DEBUG flwr 2024-10-13 12:03:08,400 | raybackend.py:141 | Constructed ActorPool with: 6 actors
dv - | DEBUG flwr 2024-10-13 12:03:08,401 | state_factory.py:50 | Using InMemoryState
dv - | DEBUG flwr 2024-10-13 12:03:08,405 | ray_actor.py:450 | Terminated 6 actors
dv - | DEBUG flwr 2024-10-13 12:03:08,883 | raybackend.py:193 | Terminated RayBackend
dv - | CRITICAL flwr 2024-10-13 12:06:22,274 | server_app.py:85 | file writing: True
dv - | CRITICAL flwr 2024-10-13 12:06:22,275 | server_app.py:86 | running in fed_agg
dv - | CRITICAL flwr 2024-10-13 12:06:22,277 | server_app.py:87 | min num clients 2
dv - | CRITICAL flwr 2024-10-13 12:06:22,278 | server_app.py:88 | num server rounds 1
dv - | CRITICAL flwr 2024-10-13 12:06:22,278 | server_app.py:89 | num local epochs 2
dv - | CRITICAL flwr 2024-10-13 12:06:22,279 | server_app.py:90 | advanced logging False
dv - | INFO flwr 2024-10-13 12:06:22,294 | app.py:74 | Starting Flower ServerApp, config: num_rounds=1, no round_timeout
dv - | INFO flwr 2024-10-13 12:06:22,323 | app.py:79 | 
dv - | INFO flwr 2024-10-13 12:06:22,404 | server.py:92 | [INIT]
dv - | INFO flwr 2024-10-13 12:06:22,434 | server.py:277 | Using initial global parameters provided by strategy
dv - | INFO flwr 2024-10-13 12:06:22,440 | server.py:94 | Starting evaluation of initial global parameters
dv - | INFO flwr 2024-10-13 12:06:22,441 | server.py:106 | Evaluation returned no results (`None`)
dv - | INFO flwr 2024-10-13 12:06:22,441 | server.py:112 | 
dv - | INFO flwr 2024-10-13 12:06:22,442 | server.py:113 | [ROUND 1]
dv - | INFO flwr 2024-10-13 12:06:22,442 | server.py:226 | configure_fit: strategy sampled 4 clients (out of 5)
dv - | DEBUG flwr 2024-10-13 12:06:30,960 | raybackend.py:141 | Constructed ActorPool with: 6 actors
dv - | DEBUG flwr 2024-10-13 12:06:30,960 | state_factory.py:50 | Using InMemoryState
dv - | INFO flwr 2024-10-13 12:07:09,962 | server.py:240 | aggregate_fit: received 4 results and 0 failures
dv - | CRITICAL flwr 2024-10-13 12:07:09,963 | fed_agg.py:124 | in place!
dv - | INFO flwr 2024-10-13 12:07:09,967 | server.py:178 | configure_evaluate: strategy sampled 4 clients (out of 5)
dv - | INFO flwr 2024-10-13 12:07:11,977 | server.py:192 | aggregate_evaluate: received 4 results and 0 failures
dv - | INFO flwr 2024-10-13 12:07:11,977 | server.py:496 | 
dv - | INFO flwr 2024-10-13 12:07:11,978 | server.py:497 | [SUMMARY]
dv - | INFO flwr 2024-10-13 12:07:11,978 | server.py:498 | Run finished 1 round(s) in 49.54s
dv - | INFO flwr 2024-10-13 12:07:11,978 | server.py:500 | 	History (loss, distributed):
dv - | INFO flwr 2024-10-13 12:07:11,978 | server.py:500 | 		round 1: 139.2227395192682
dv - | INFO flwr 2024-10-13 12:07:11,978 | server.py:500 | 	History (metrics, distributed, evaluate):
dv - | INFO flwr 2024-10-13 12:07:11,979 | server.py:500 | 	{'accuracy': [(1, 0.19783895034731155)], 'count': [(1, 4)]}
dv - | INFO flwr 2024-10-13 12:07:11,979 | server.py:501 | 
dv - | DEBUG flwr 2024-10-13 12:07:11,980 | run_serverapp.py:90 | ServerApp finished running.
dv - | DEBUG flwr 2024-10-13 12:07:11,980 | run_simulation.py:349 | ServerApp finished running.
dv - | DEBUG flwr 2024-10-13 12:07:11,980 | run_simulation.py:353 | Triggered stop event for Simulation Engine.
dv - | DEBUG flwr 2024-10-13 12:07:12,792 | ray_actor.py:450 | Terminated 6 actors
dv - | DEBUG flwr 2024-10-13 12:07:13,554 | raybackend.py:193 | Terminated RayBackend
dv - | DEBUG flwr 2024-10-13 12:07:13,555 | run_simulation.py:455 | Stopping Simulation Engine now.
